name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Extract version
        id: getversion
        run: |
          Get-ChildItem 
          $xml = [xml](Get-Content BarelyFunctional/BarelyFunctional.csproj)
          $version = $xml.Project.PropertyGroup.Version
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$version"
        shell: pwsh
        
      - name: Check version
        id: checkversion
        continue-on-error: true
        run: |
          pwsh ./.github/scripts/CheckVersion.ps1 -githubRepository ${{ github.repository }} -version $env:VERSION -accessToken $env:ACCESS_TOKEN
        shell: pwsh
        env:
          VERSION: ${{ env.VERSION }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release --output ./nupkg

      - name: List package files
        run: Get-ChildItem ./nupkg

      - name: Publish to NuGet
        run: nuget push ./nupkg/BarelyFunctional.${{ env.VERSION }}.nupkg -NonInteractive -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json